/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.ActivitateDB;
import db.EchipaDB;
import db.FakeActivitateDB;
import db.FakeJocDB;
import db.JocDB;
import dialogs.PermissionFrame;
import dto.UserDTO;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import service.ControllerDB;

/**
 *
 * @author Alexandru
 */
public class ViewActivitatiFrame extends javax.swing.JFrame {
    private ComboBoxModel<String> combo;
    private DefaultListModel<ActivitateDB> activitatiModel;
    private DefaultListModel<JocDB> jocuriModel;
    private DefaultListModel<EchipaDB> echipeModel;
    private EchipaDB echipa;
    private List<ActivitateDB> activitati;
    private List<JocDB> jocuri;
    private List<FakeActivitateDB> fakeAct;
    private List<FakeJocDB> fakeJoc;
    private boolean inactiv;
    private boolean autentificat = false;
    /**
     * Creates new form ViewActivitatiFrame
     * 
     * @param echipa
     * @param inactiv
     */
    public ViewActivitatiFrame(EchipaDB echipa, boolean inactiv) {
        super ("Activitati si Jocuri : Echipa " + echipa.getNumeEchipa());
        initComponents();
        
        this.echipa = echipa;
        this.inactiv = inactiv;
        activitati = ControllerDB.getInstance().getActivittatiByEchipa(echipa);
        jocuri = ControllerDB.getInstance().getJocuriByEchipa(echipa);
        
        activitatiModel = new DefaultListModel<>();
        jocuriModel = new DefaultListModel<>();
        echipeModel = new DefaultListModel<>();
        combo = new DefaultComboBoxModel<String>(new String [] {"Activitati", "Jocuri"});
        combo.setSelectedItem("Activitati");
        
        populateModels();
        
        jList1.setModel(activitatiModel);
        jComboBox1.setModel(combo);
        
        jList2.setModel(echipeModel);
        jList2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        jLabel5.setVisible(false);
        jLabel10.setVisible(false);
        
        jLabel6.setText("");
        jLabel7.setText("");
        jLabel7.setToolTipText(null);
        jLabel8.setText("");
        jLabel9.setText("");
        jLabel10.setText("");
        jLabel12.setText("");
        jLabel15.setText("");
        jLabel17.setText("");
        
        jMenuItem1.setText("Sterge");
        
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }
    
    public final void populateModels () {
        String lastDate = "";
        fakeAct = new ArrayList<>();
        FakeActivitateDB fakeA = null;
        
        for (int i = 0; i < activitati.size(); ++i) {
            if (!activitati.get(i).getData().equals(lastDate)){
                if (fakeA != null) {
                    fakeAct.add(fakeA);
                }
                lastDate = activitati.get(i).getData();
                fakeA = new FakeActivitateDB(lastDate);
            } 
            
            if (fakeA != null) {
                fakeA.addActivitate(activitati.get(i));
            }            
        }
        
        if (fakeA != null) {
            fakeAct.add(fakeA);
        }
        
        lastDate = "";
        fakeJoc = new ArrayList<>();
        FakeJocDB fakeJ = null;
        
        for (int i = 0; i < jocuri.size(); ++i) {
            if (!jocuri.get(i).getData().equals(lastDate)) {
                if (fakeJ != null) {
                    fakeJoc.add(fakeJ);
                }
                lastDate = jocuri.get(i).getData();
                fakeJ = new FakeJocDB(lastDate);
            }
            
            if (fakeJ != null) {
                fakeJ.addJoc(jocuri.get(i));
            }
        }
        
        if (fakeJ != null) {
            fakeJoc.add(fakeJ);
        }
        
        for (FakeActivitateDB f : fakeAct) {
            activitatiModel.addElement(f);
            for (ActivitateDB a : f.getActivitati()) {
                activitatiModel.addElement(a);
            }            
        }
        
        for (FakeJocDB f : fakeJoc) {
            jocuriModel.addElement(f);
            for (JocDB j : f.getJocuri()) {
                jocuriModel.addElement(j);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Data :");

        jLabel2.setText("Organizatori :");

        jLabel3.setText("Locatie :");

        jLabel4.setText("Post :");

        jLabel5.setText("Punctaj :");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel6");

        jLabel8.setText("jLabel6");

        jLabel9.setText("jLabel6");

        jLabel10.setText("jLabel6");

        jLabel11.setText("Activitatea :");

        jLabel12.setText("jLabel12");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nota"));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("<html>\"*\" - marcheaza un animator care si-a finalizat activitatea</html>");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel13.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jLabel14.setText("Perioada :");

        jLabel15.setText("jLabel6");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Alte echipe care au realizat activitatea"));

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jList2MouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jLabel16.setText("ID Program :");

        jLabel17.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox1MouseEntered(evt);
            }
        });
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jList1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jComboBox1, 0, 200, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (combo.getSelectedItem() == "Activitati") {
            jList1.setModel(activitatiModel);
            jLabel5.setVisible(false);
            jLabel10.setVisible(false);
        } else {
            jList1.setModel(jocuriModel);
            jLabel5.setVisible(true);
            jLabel10.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if (jList1.getSelectedValue() == null) return;
        
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (combo.getSelectedItem() == "Activitati") {
                if (jList1.getSelectedValue().getClass() == FakeActivitateDB.class && evt.getClickCount() == 2) {
                    FakeActivitateDB fakeA = (FakeActivitateDB) jList1.getSelectedValue();
                    if (jList1.getSelectedIndex() < activitatiModel.getSize() - 1) {
                        if (!(activitatiModel.getElementAt(jList1.getSelectedIndex() + 1).getClass() == FakeActivitateDB.class)) {
                            for (ActivitateDB a : fakeA.getActivitati()) {
                                activitatiModel.removeElement(a);
                            }
                        } else {
                            int index = jList1.getSelectedIndex() + 1;
                            for (int i = 0; i < fakeA.getActivitati().size(); ++i) {
                                activitatiModel.add(index+i, fakeA.getActivitati().get(i));
                            }
                        }
                    } else {
                        int index = jList1.getSelectedIndex() + 1;
                            for (int i = 0; i < fakeA.getActivitati().size(); ++i) {
                                activitatiModel.add(index+i, fakeA.getActivitati().get(i));
                            }
                    }

                    jLabel6.setText("");
                    jLabel7.setText("");
                    jLabel7.setToolTipText(null);
                    jLabel8.setText("");
                    jLabel9.setText("");
                    jLabel10.setText("");
                    jLabel12.setText("");
                    jLabel15.setText("");
                    jLabel17.setText("");
                    echipeModel.clear();
                    jList2.setModel(echipeModel);
                } else if (jList1.getSelectedValue().getClass() == ActivitateDB.class) {
                    ActivitateDB a = (ActivitateDB) jList1.getSelectedValue();
                    jLabel6.setText(a.getData());
                    jLabel7.setText(a.getOrganizator());
                    jLabel7.setToolTipText(a.getOrganizator());
                    String perioada = a.getLoactie().subSequence(a.getLoactie().indexOf("$") + 1, a.getLoactie().lastIndexOf("$")).toString();
                    jLabel8.setText(a.getLoactie().replace("$" + perioada + "$", ""));
                    jLabel15.setText(perioada);
                    jLabel9.setText(a.getPost());
                    jLabel12.setText(a.toString());    
                    jLabel17.setText(a.getIdProgram() + "");
                    echipeModel.clear();
                    List<ActivitateDB> storedActivitati = ControllerDB.getInstance().getStoredActivitateByIdProgram(perioada, a.getActivitateGeneralaidActivitateGenerala(), a.getIdProgram());
                    for (ActivitateDB adb : storedActivitati) {
                        if (!adb.getEchipaidEchipa().equals(echipa)) {
                            echipeModel.addElement(adb.getEchipaidEchipa());
                        }
                    }
                    jList2.setModel(echipeModel);
                }
            } else {
                if (jList1.getSelectedValue().getClass() == FakeJocDB.class && evt.getClickCount() == 2) {
                    FakeJocDB fakeA = (FakeJocDB) jList1.getSelectedValue();
                    if (jList1.getSelectedIndex() < jocuriModel.getSize() - 1) {
                        if (jocuriModel.getElementAt(jList1.getSelectedIndex() + 1).getClass() == JocDB.class) {
                            for (JocDB a : fakeA.getJocuri()) {
                                jocuriModel.removeElement(a);
                            }
                        } else {
                            int index = jList1.getSelectedIndex() + 1;
                            for (int i = 0; i < fakeA.getJocuri().size(); ++i) {
                                jocuriModel.add(index+i, fakeA.getJocuri().get(i));
                            }
                        }
                    } else {
                        int index = jList1.getSelectedIndex() + 1;
                            for (int i = 0; i < fakeA.getJocuri().size(); ++i) {
                                jocuriModel.add(index+i, fakeA.getJocuri().get(i));
                            }
                    }

                    jLabel6.setText("");
                    jLabel7.setText("");
                    jLabel7.setToolTipText(null);
                    jLabel8.setText("");
                    jLabel9.setText("");
                    jLabel10.setText("");
                    jLabel12.setText("");
                    jLabel15.setText("");
                    jLabel17.setText("");
                    echipeModel.clear();
                    jList2.setModel(echipeModel);
                } else if (jList1.getSelectedValue().getClass() == JocDB.class) {
                    JocDB a = (JocDB) jList1.getSelectedValue();
                    jLabel6.setText(a.getData());
                    jLabel7.setText(a.getOrganizator());
                    jLabel7.setToolTipText(a.getOrganizator());
                    String perioada = a.getLocatie().subSequence(a.getLocatie().indexOf("$") + 1, a.getLocatie().lastIndexOf("$")).toString();
                    jLabel8.setText(a.getLocatie().replace("$" + perioada + "$", ""));
                    jLabel15.setText(perioada);
                    jLabel9.setText(a.getPost());
                    jLabel10.setText(a.getPunctaj() + "" + (a.getAbsent() == true ? "(absent)" : ""));
                    jLabel12.setText(a.toString());
                    jLabel17.setText(a.getIdProgram() + "");
                    
                    echipeModel.clear();
                    List<JocDB> storedJocuri = ControllerDB.getInstance().getStoredJocByIdProgram(perioada, a.getJocGeneralidJocGeneral(), a.getIdProgram());
                    for (JocDB jdb : storedJocuri) {
                        if (!jdb.getEchipaidEchipa().equals(echipa)) {
                            echipeModel.addElement(jdb.getEchipaidEchipa());
                        }
                    }
                    jList2.setModel(echipeModel);
                }
            }
        } else if (evt.getButton() == MouseEvent.BUTTON3 && !inactiv) {
            if (jList1.getSelectedValue().getClass() == JocDB.class) {
                jPopupMenu1.show(jList1, evt.getX(), evt.getY());
            }            
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        final JocDB selected = (JocDB) jList1.getSelectedValue();
        
        if (!autentificat) {
            PermissionFrame perm = new PermissionFrame(this, true, "Confirmati stergerea jocului", UserDTO.ACCES_COORDONATOR);
            if (perm.isApproved()) {
                autentificat = true;
            }
        }
        
        if (autentificat) {
            boolean rez = ControllerDB.getInstance().stergeJoc(selected);
            if (rez) {
                FakeJocDB master = null;
                int index = jList1.getSelectedIndex();
                int i;
                for (i = index; i >= 0; --i){
                    if (jocuriModel.get(i).getClass() == FakeJocDB.class){
                        master = (FakeJocDB) jocuriModel.get(i);
                        break;
                    }
                }
                
                if (master != null) {
                    master.getJocuri().remove(selected);
                }
                
                jocuriModel.removeElement(selected);
                jList1.setModel(jocuriModel);
                jLabel6.setText("");
                jLabel7.setText("");
                jLabel7.setToolTipText(null);
                jLabel8.setText("");
                jLabel9.setText("");
                jLabel10.setText("");
                jLabel12.setText("");
                jLabel15.setText("");
                jLabel17.setText("");
                echipeModel.clear();
                jList2.setModel(echipeModel);
            } else {
                JOptionPane.showMessageDialog(this, "Jocul nu a putut fi sters : ", null, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        if (jList2.getSelectedValue() != null && evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() == 2) {
            new ViewActivitatiFrame((EchipaDB) jList2.getSelectedValue(), inactiv).setVisible(true);
        }
    }//GEN-LAST:event_jList2MouseClicked

    private void jComboBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseEntered
        HelperFrame.getInstance().post(
                "Meniul tipului de activitate",
                "De aici poti selecta daca doresti sa vizualizezi lista activitatilor (standard) sau a jocurilor.");
    }//GEN-LAST:event_jComboBox1MouseEntered

    private void jList1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseEntered
        HelperFrame.getInstance().post(
                "Arbore activitati",
                "Aici poti vedea toate activitatile ordonate cronologic, puse in subfoldere denumite dupa data in care "
                        + "au avut loc toate activitatile din acesta. \n"
                        + " Dublu-click pe o data pentru a desfasura activitatile din acea zi.\n"
                        + " Click pe activitate pentru a-i vizualiza detaliile. \n"
                        + " Click dreapta pe o activitate pentru mai multe optiuni.");
    }//GEN-LAST:event_jList1MouseEntered

    private void jList2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseEntered
        HelperFrame.getInstance().post(
                "Echipe participante",
                "Lista celorlalte echipe care au finalizat activitatea selectata.");
    }//GEN-LAST:event_jList2MouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
