/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.SwingWorker;
import main.Event;
import service.Zipper;

/**
 *
 * @author Alexandru
 */
public class ZippingFrame extends javax.swing.JDialog {
    private final static int STANDARD_WIDTH = 367;
    private final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy - HH:mm:ss -> ");
    private final Zipper zipper;
    private final MainFrame mFrame;
    private DefaultListModel<String> model;
    private boolean init = false;
    private Event doneEvent;
    
    /**
     * Creates new form LoadingFrame
     * @param zipper
     * @param parent
     * @param model
     */
    public ZippingFrame(Zipper zipper, Frame parent, boolean model) {
        super(parent, model);
        initComponents();
        
        this.zipper = zipper;
        this.mFrame = (MainFrame) parent;
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        jList1.setAutoscrolls(true);
        jList1.setFixedCellWidth(STANDARD_WIDTH);
        jButton1.setVisible(false);
    }
    
    public void initZipper () {
        model = new DefaultListModel<>();
        jProgressBar1.setValue(0);
        
        model.addElement(sdf.format(Calendar.getInstance().getTime()) + "Se incepe progesul");
        
        jList1.setModel(model);
        setVisible(true);
        init = true;
    }

    public void setDoneEvent (Event doneEvent) {
        this.doneEvent = doneEvent;
    }
    
    public void start () {
        if (!init) initZipper();
        new Task().execute();
    }
    
    public void updateBar (int i) {
        jProgressBar1.setValue(i);
    }
    
    public void updateList (String message) {
        model.addElement(sdf.format(Calendar.getInstance().getTime()) + message);
        jList1.setModel(model);
        jList1.ensureIndexIsVisible(model.size()-1);
    }
    
    private class Task extends SwingWorker<Void, Void> {

        @Override
        protected Void doInBackground() throws Exception {
            zipper.zip(ZippingFrame.this);
            return null;
        }
        
        @Override
        protected void done () {
            updateList("Gata!");
            if (doneEvent != null) {
                dispose();
                doneEvent.doAction();
                return;
            }
            jButton1.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Arhivare...");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jProgressBar1.setForeground(new java.awt.Color(0, 204, 51));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Gata");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        mFrame.doneZipping(zipper.getOutPath());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList jList1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
